#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
panel &
pulseaudio --start &
polybar &
nm-applet &

xinput set-prop "ASUP1201:00 093A:1001 Touchpad" "libinput Tapping Enabled" 1
feh --bg-fill $HOME/Pictures/wp9081278.jpeg &
picom --config $HOME/.config/picom/picom.conf &
xrandr --output eDP-1 --set "color vibrance" 150 &
wal -i $HOME/.config/picom/picom.conf &
betterlockscreen -u /home/hannese/Pictures/wp9081278.jpeg

eval $(gnome-keyring-daemon --start --components=secrets)
export SSH_AUTH_SOCK

#activate-linux -c 0.3-0.3-0.3-0.7 &

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width         2
bspc config window_gap           7

bspc config focus_follows_pointer true

bspc config border_width 2
bspc config border_radius 5
bspc config top_padding 28

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a krunner state=floating layer=above sticky=on border=off
bspc rule -a SessionDialog state=floating center=true
bspc rule -a BrightnessDialog state=floating center=true focus=off
bspc rule -a Tkinter state=floating center=true
